DATASET_MODULES = (
    "CNC",
    "CWRU",
    "FEMTO",
    "HITSM",
    "HUST_Bearing",
    "HUST_Gearbox",
    "HUST_Motor",
    "IMS_FD",
    "JNU",
    "KAIST",
    "MCC5_THU_Gearbox",
    "MCC5_THU_Motor",
    "MFPT",
    "PU",
    "SDUST_Bearing",
    "SDUST_Gear",
    "SEU",
    "TORINO",
    "UO",
    "WT",
    "XJTUSY",
)

DATASET_ALIASES = {
    "hit-sm": "HITSM",
    "hit-motor": "HUST_Motor",
    "hit_motor": "HUST_Motor",
    "ims": "IMS_FD",
    "imsfd": "IMS_FD",
    "mcc5": "MCC5_THU_Gearbox",
    "mcc5-thu-gearbox": "MCC5_THU_Gearbox",
    "mcc5_thu_gearbox": "MCC5_THU_Gearbox",
    "mcc5-thu-motor": "MCC5_THU_Motor",
    "mcc5-thu_motor": "MCC5_THU_Motor",
    "mcc5_thu_motor": "MCC5_THU_Motor",
    "sdust-bearing": "SDUST_Bearing",
    "sdust_bearing": "SDUST_Bearing",
    "sdust-gear": "SDUST_Gear",
    "sdust_gear": "SDUST_Gear",
    "sudst-bearing": "SDUST_Bearing",
    "sudst_bearing": "SDUST_Bearing",
    "sudst-gear": "SDUST_Gear",
    "sudst_gear": "SDUST_Gear",
    "xjtu-sy": "XJTUSY",
    "xjtu_sy": "XJTUSY",
}
